#!/usr/bin/env bash
# /***************************************************************************/
# /* Copyright (C) 2026 Eclipse ThreadX contributors
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the MIT License which is available at
#  * https://opensource.org/licenses/MIT.
#  *
#  * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
#  * The AI-generated portions may be considered public domain (CC0-1.0)
#  * and not subject to the project's licence.
#  *
#  * SPDX-License-Identifier: MIT and CC0-1.0
#  ***************************************************************************/

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"
rm -rf "${BUILD_DIR}"
cmake -S "${SCRIPT_DIR}" -B "${BUILD_DIR}" \
    -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="${SCRIPT_DIR}/../../libs/threadx/cmake/riscv64-gcc-rv32imc.cmake" \
    -DCMAKE_BUILD_TYPE=Debug
cmake --build "${BUILD_DIR}"
echo "=== Sections ==="
riscv64-unknown-elf-size "${BUILD_DIR}/core_v_mcu_cli_test.elf"
echo "=== Done ==="
