/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

/* Pull in platform declarations needed by verbatim-copied CLI library sources. */
#include "SDKConfig.h"

#define configTICK_RATE_HZ                         (100U)
#define configMAX_PRIORITIES                       (32U)
#define configMINIMAL_STACK_SIZE                   (512U)
#define configTOTAL_HEAP_SIZE                      (1024U * 64U)
#define configUSE_16_BIT_TICKS                     0
#define configSTACK_DEPTH_TYPE                     uint32_t
#define INCLUDE_vTaskDelete                        1
#define portDISABLE_INTERRUPTS()                   _tx_thread_interrupt_control(TX_INT_DISABLE)
#define portENABLE_INTERRUPTS()                    _tx_thread_interrupt_control(TX_INT_ENABLE)
#define configASSERT(x)
#define TX_FREERTOS_ASSERT_FAIL()
#define TX_FREERTOS_AUTO_INIT                      0

#endif /* FREERTOS_CONFIG_H */
