/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include "string.h"
#include "stdlib.h"

/* Return non-zero if the character is ASCII whitespace. */
static int compat_is_space(char c)
{
    return ((c == ' ') || (c == '\t') || (c == '\n') || (c == '\r') || (c == '\f') || (c == '\v')) ? 1 : 0;
}

/* Return non-zero if the character matches any delimiter in the set. */
static int compat_is_delim(char c, const char *delim)
{
    while ((delim != NULL) && (*delim != '\0'))
    {
        if (*delim == c)
        {
            return 1;
        }
        ++delim;
    }

    return 0;
}

/* Convert a single ASCII digit into its numeric value. */
static int compat_digit_value(char c)
{
    if ((c >= '0') && (c <= '9'))
    {
        return (int)(c - '0');
    }
    if ((c >= 'a') && (c <= 'f'))
    {
        return 10 + (int)(c - 'a');
    }
    if ((c >= 'A') && (c <= 'F'))
    {
        return 10 + (int)(c - 'A');
    }

    return -1;
}

/* Parse an unsigned integer from a string. */
unsigned long long strtoull(const char *nptr, char **endptr, int base)
{
    const char *p;
    unsigned long long value;
    int digit;
    int any;

    p = nptr;
    value = 0U;
    any = 0;

    while ((p != NULL) && compat_is_space(*p) != 0)
    {
        ++p;
    }
    if ((p != NULL) && (*p == '+'))
    {
        ++p;
    }

    if ((base == 0) || (base == 16))
    {
        if ((p[0] == '0') && ((p[1] == 'x') || (p[1] == 'X')))
        {
            p += 2;
            base = 16;
        }
    }
    if (base == 0)
    {
        base = (p[0] == '0') ? 8 : 10;
    }

    while (*p != '\0')
    {
        digit = compat_digit_value(*p);
        if ((digit < 0) || (digit >= base))
        {
            break;
        }
        value = (value * (unsigned long long)base) + (unsigned long long)digit;
        ++p;
        any = 1;
    }

    if (endptr != NULL)
    {
        *endptr = (char *)((any != 0) ? p : nptr);
    }

    return value;
}

/* Parse a signed integer from a string. */
long long strtoll(const char *nptr, char **endptr, int base)
{
    const char *p;
    unsigned long long magnitude;
    int negative;
    char *local_end;

    p = nptr;
    negative = 0;

    while ((p != NULL) && compat_is_space(*p) != 0)
    {
        ++p;
    }
    if ((p != NULL) && ((*p == '+') || (*p == '-')))
    {
        negative = (*p == '-') ? 1 : 0;
        ++p;
    }

    magnitude = strtoull(p, &local_end, base);
    if (endptr != NULL)
    {
        *endptr = (local_end == p) ? (char *)nptr : local_end;
    }

    return (negative != 0) ? -(long long)magnitude : (long long)magnitude;
}

/* Parse a floating-point value from a string. */
float strtof(const char *nptr, char **endptr)
{
    const char *p;
    double value;
    double frac_scale;
    double factor;
    int exponent;
    int negative;
    int any;

    p = nptr;
    value = 0.0;
    frac_scale = 0.1;
    exponent = 0;
    negative = 0;
    any = 0;

    while ((p != NULL) && compat_is_space(*p) != 0)
    {
        ++p;
    }
    if ((p != NULL) && ((*p == '+') || (*p == '-')))
    {
        negative = (*p == '-') ? 1 : 0;
        ++p;
    }

    while ((*p >= '0') && (*p <= '9'))
    {
        value = (value * 10.0) + (double)(*p - '0');
        ++p;
        any = 1;
    }

    if (*p == '.')
    {
        ++p;
        while ((*p >= '0') && (*p <= '9'))
        {
            value += ((double)(*p - '0')) * frac_scale;
            frac_scale *= 0.1;
            ++p;
            any = 1;
        }
    }

    if (((*p == 'e') || (*p == 'E')) && any != 0)
    {
        const char *exp_start;
        int exp_negative;
        int exp_any;

        exp_start = p;
        exp_negative = 0;
        exp_any = 0;
        ++p;
        if ((*p == '+') || (*p == '-'))
        {
            exp_negative = (*p == '-') ? 1 : 0;
            ++p;
        }
        while ((*p >= '0') && (*p <= '9'))
        {
            exponent = (exponent * 10) + (int)(*p - '0');
            ++p;
            exp_any = 1;
        }
        if (exp_any == 0)
        {
            p = exp_start;
        }
        else
        {
            factor = 1.0;
            while (exponent > 0)
            {
                factor *= 10.0;
                --exponent;
            }
            value = (exp_negative != 0) ? (value / factor) : (value * factor);
        }
    }

    if (negative != 0)
    {
        value = -value;
    }

    if (endptr != NULL)
    {
        *endptr = (char *)((any != 0) ? p : nptr);
    }

    return (float)value;
}

/* Return the length of a string. */
size_t strlen(const char *s)
{
    size_t len;

    len = 0U;
    while ((s != NULL) && (s[len] != '\0'))
    {
        ++len;
    }

    return len;
}

/* Compare two strings lexicographically. */
int strcmp(const char *lhs, const char *rhs)
{
    while ((*lhs != '\0') && (*rhs != '\0') && (*lhs == *rhs))
    {
        ++lhs;
        ++rhs;
    }

    return (int)(unsigned char)*lhs - (int)(unsigned char)*rhs;
}

/* Compare at most n characters of two strings. */
int strncmp(const char *lhs, const char *rhs, size_t n)
{
    size_t i;

    for (i = 0U; i < n; ++i)
    {
        if ((lhs[i] != rhs[i]) || (lhs[i] == '\0') || (rhs[i] == '\0'))
        {
            return (int)(unsigned char)lhs[i] - (int)(unsigned char)rhs[i];
        }
    }

    return 0;
}

/* Tokenize a string using a caller-provided save pointer. */
char *strtok_r(char *str, const char *delim, char **saveptr)
{
    char *token;
    char *p;

    p = (str != NULL) ? str : ((saveptr != NULL) ? *saveptr : NULL);
    if (p == NULL)
    {
        return NULL;
    }

    while ((*p != '\0') && (compat_is_delim(*p, delim) != 0))
    {
        ++p;
    }
    if (*p == '\0')
    {
        if (saveptr != NULL)
        {
            *saveptr = p;
        }
        return NULL;
    }

    token = p;
    while ((*p != '\0') && (compat_is_delim(*p, delim) == 0))
    {
        ++p;
    }
    if (*p != '\0')
    {
        *p = '\0';
        ++p;
    }
    if (saveptr != NULL)
    {
        *saveptr = p;
    }

    return token;
}
