/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef APP_COMMANDS_H
#define APP_COMMANDS_H

#include "libs/cli/include/cli.h"

/* Return the top-level CLI menu for the sample application. */
const struct cli_cmd_entry *app_get_menu(void);

#endif /* APP_COMMANDS_H */
