/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include <stdint.h>

#include "app_commands.h"
#include "gpio.h"
#include "uart_driver.h"

/* ── misc ───────────────────────────────────────────────────────────────── */

static void do_version(const struct cli_cmd_entry *pEntry)
{
    (void)pEntry;
    CLI_printf("CORE-V MCU ThreadX CLI Demo\n");
    CLI_printf("Build: %s %s\n", __DATE__, __TIME__);
}

static const struct cli_cmd_entry misc_menu[] = {
    CLI_CMD_SIMPLE("version", do_version, "Print firmware version and build time"),
    CLI_CMD_TERMINATE()
};

/* ── mem ────────────────────────────────────────────────────────────────── */

static void do_mem_peek(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_printf("value 0x%08x\n", *(volatile uint32_t *)addr);
}

static void do_mem_poke(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    uint32_t value;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_uint32_required("value", &value);
    *(volatile uint32_t *)addr = value;
    CLI_printf("<<DONE>>\n");
}

static void do_mem_peek8(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_printf("value 0x%02x\n", *(volatile uint8_t *)addr);
}

static void do_mem_poke8(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    uint32_t value;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_uint32_required("value", &value);
    *(volatile uint8_t *)addr = (uint8_t)value;
    CLI_printf("<<DONE>>\n");
}

static void do_mem_peek16(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_printf("value 0x%04x\n", *(volatile uint16_t *)addr);
}

static void do_mem_poke16(const struct cli_cmd_entry *pEntry)
{
    uint32_t addr;
    uint32_t value;
    (void)pEntry;
    CLI_uint32_required("addr", &addr);
    CLI_uint32_required("value", &value);
    *(volatile uint16_t *)addr = (uint16_t)value;
    CLI_printf("<<DONE>>\n");
}

static const struct cli_cmd_entry mem_menu[] = {
    CLI_CMD_SIMPLE("peek",  do_mem_peek,   "0xaddr -- read 32-bit word"),
    CLI_CMD_SIMPLE("poke",  do_mem_poke,   "0xaddr 0xval -- write 32-bit word"),
    CLI_CMD_SIMPLE("md.b",  do_mem_peek8,  "0xaddr -- read 8-bit byte"),
    CLI_CMD_SIMPLE("mw.b",  do_mem_poke8,  "0xaddr 0xval -- write 8-bit byte"),
    CLI_CMD_SIMPLE("md.w",  do_mem_peek16, "0xaddr -- read 16-bit halfword"),
    CLI_CMD_SIMPLE("mw.w",  do_mem_poke16, "0xaddr 0xval -- write 16-bit halfword"),
    CLI_CMD_SIMPLE("md.l",  do_mem_peek,   "0xaddr -- read 32-bit word"),
    CLI_CMD_SIMPLE("mw.l",  do_mem_poke,   "0xaddr 0xval -- write 32-bit word"),
    CLI_CMD_TERMINATE()
};

/* ── io ─────────────────────────────────────────────────────────────────── */

static void do_io_setmux(const struct cli_cmd_entry *pEntry)
{
    uint32_t io_pad;
    uint32_t mux;
    uint8_t readback;
    (void)pEntry;
    CLI_uint32_required("io_pad", &io_pad);
    CLI_uint32_required("mux_sel", &mux);
    gpio_setpinmux((uint8_t)io_pad, (uint8_t)mux);
    readback = gpio_getpinmux((uint8_t)io_pad);
    if (readback == (uint8_t)mux)
    {
        CLI_printf("io setmux %d <<PASSED>>\n", io_pad);
    }
    else
    {
        CLI_printf("io setmux %d <<FAILED>> (readback=0x%x)\n", io_pad, readback);
    }
}

static void do_io_getmux(const struct cli_cmd_entry *pEntry)
{
    uint32_t io_pad;
    (void)pEntry;
    CLI_uint32_required("io_pad", &io_pad);
    CLI_printf("mux_sel 0x%x\n", gpio_getpinmux((uint8_t)io_pad));
}

static const struct cli_cmd_entry io_menu[] = {
    CLI_CMD_SIMPLE("setmux", do_io_setmux, "io_pad mux_sel -- set pad mux function"),
    CLI_CMD_SIMPLE("getmux", do_io_getmux, "io_pad -- read pad mux function"),
    CLI_CMD_TERMINATE()
};

/* ── gpio ───────────────────────────────────────────────────────────────── */

static void do_gpio_set(const struct cli_cmd_entry *pEntry)
{
    uint32_t pin;
    (void)pEntry;
    CLI_uint32_required("gpio_num", &pin);
    gpio_set(1UL << pin);
    CLI_printf("<<DONE>>\n");
}

static void do_gpio_clr(const struct cli_cmd_entry *pEntry)
{
    uint32_t pin;
    (void)pEntry;
    CLI_uint32_required("gpio_num", &pin);
    gpio_clear(1UL << pin);
    CLI_printf("<<DONE>>\n");
}

static void do_gpio_toggle(const struct cli_cmd_entry *pEntry)
{
    uint32_t pin;
    (void)pEntry;
    CLI_uint32_required("gpio_num", &pin);
    gpio_toggle(1UL << pin);
    CLI_printf("<<DONE>>\n");
}

static void do_gpio_mode(const struct cli_cmd_entry *pEntry)
{
    uint32_t pin;
    uint32_t mode;
    (void)pEntry;
    CLI_uint32_required("gpio_num", &pin);
    CLI_uint32_required("gpio_mode", &mode);
    gpio_pin_set_dir((uint8_t)pin, (uint8_t)mode);
    CLI_printf("<<DONE>>\n");
}

static void do_gpio_status(const struct cli_cmd_entry *pEntry)
{
    uint32_t pin;
    uint32_t stat;
    (void)pEntry;
    CLI_uint32_required("gpio_num", &pin);
    stat = gpio_pin_read_status((uint8_t)pin);
    CLI_printf("input            0x%x\n", (stat >> 12U) & 0x1U);
    CLI_printf("output           0x%x\n", (stat >>  8U) & 0x1U);
    CLI_printf("interrupt_enable 0x%x\n", (stat >> 16U) & 0x1U);
    CLI_printf("interrupt_type   0x%x\n", (stat >> 17U) & 0x7U);
    CLI_printf("gpio_mode        0x%x\n", (stat >> 24U) & 0x3U);
    CLI_printf("rdstat           0x%08x\n", stat);
}

static const struct cli_cmd_entry gpio_menu[] = {
    CLI_CMD_SIMPLE("set",    do_gpio_set,    "gpio_num -- drive pin high"),
    CLI_CMD_SIMPLE("clr",    do_gpio_clr,    "gpio_num -- drive pin low"),
    CLI_CMD_SIMPLE("toggle", do_gpio_toggle, "gpio_num -- toggle pin"),
    CLI_CMD_SIMPLE("mode",   do_gpio_mode,   "gpio_num mode (0=in,1=out) -- set direction"),
    CLI_CMD_SIMPLE("status", do_gpio_status, "gpio_num -- read pin status"),
    CLI_CMD_TERMINATE()
};

/* ── main menu ──────────────────────────────────────────────────────────── */

static const struct cli_cmd_entry app_main_menu[] = {
    CLI_CMD_SUBMENU("misc", misc_menu, "miscellaneous commands"),
    CLI_CMD_SUBMENU("mem",  mem_menu,  "memory peek/poke"),
    CLI_CMD_SUBMENU("io",   io_menu,   "IO pad mux control"),
    CLI_CMD_SUBMENU("gpio", gpio_menu, "GPIO pin control"),
    CLI_CMD_TERMINATE()
};

const struct cli_cmd_entry *app_get_menu(void)
{
    return &app_main_menu[0];
}
