/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef POLARFIRE_CONSOLE_H
#define POLARFIRE_CONSOLE_H

/*
 * Board-private console plumbing. This header is internal to the PolarFire
 * BSP: it lives beside the driver rather than in bsp/include/bsp/ because no
 * application should reach for it.
 */

/**
 * @brief Hands one received byte to the registered bsp/console.h RX handler.
 *
 * Called by trap_handler() from machine-mode interrupt context once MMUART1
 * has raised its PLIC source. Drops the byte when no handler is attached, so
 * the trap path never depends on a symbol the application must define.
 *
 * @param c The byte read out of the MMUART1 receive holding register.
 */
void polarfire_console_rx_dispatch(char c);

#endif /* POLARFIRE_CONSOLE_H */
