/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef COMPAT_SETJMP_H
#define COMPAT_SETJMP_H

#include <stdint.h>

typedef intptr_t jmp_buf[5];

#define setjmp(env) __builtin_setjmp((intptr_t *)(env))
#define longjmp(env, val) __builtin_longjmp((intptr_t *)(env), 1)

#endif /* COMPAT_SETJMP_H */
