#!/usr/bin/env bash
# /***************************************************************************/
# /* Copyright (C) 2026 Eclipse ThreadX contributors
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the MIT License which is available at
#  * https://opensource.org/licenses/MIT.
#  *
#  * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
#  * The AI-generated portions may be considered public domain (CC0-1.0)
#  * and not subject to the project's licence.
#  *
#  * SPDX-License-Identifier: MIT AND CC0-1.0
#  ***************************************************************************/

# setup_opella.sh -- one-time host configuration for the Ashling Opella LD debug probe.
#
# Usage:
#   sudo bash setup_opella.sh     # native Linux (writes udev rule, adds plugdev)
#   bash setup_opella.sh          # WSL (also attempts usbipd-win attach)
#
# The script is idempotent: safe to run more than once.

set -euo pipefail

OPELLA_VID="0b6b"
OPELLA_PID="0040"
UDEV_RULE_FILE="/etc/udev/rules.d/99-ashling-opella.rules"
UDEV_RULE='SUBSYSTEM=="usb", ATTRS{idVendor}=="0b6b", ATTRS{idProduct}=="0040", MODE="0664", GROUP="plugdev"'

info()  { echo "[INFO]  $*"; }
warn()  { echo "[WARN]  $*" >&2; }
die()   { echo "[ERROR] $*" >&2; exit 1; }

is_wsl() {
    grep -qi microsoft /proc/version 2>/dev/null || [ -n "${WSL_DISTRO_NAME:-}" ]
}

# ── udev rules ────────────────────────────────────────────────────────────────

setup_udev() {
    info "Writing udev rule to ${UDEV_RULE_FILE} ..."
    if [ "$(id -u)" -ne 0 ]; then
        info "Not running as root -- re-invoking with sudo for udev changes ..."
        sudo bash "$0" --udev-only
        return
    fi

    echo "${UDEV_RULE}" > "${UDEV_RULE_FILE}"
    chmod 644 "${UDEV_RULE_FILE}"
    info "Wrote: ${UDEV_RULE_FILE}"

    TARGET_USER="${SUDO_USER:-${USER}}"
    info "Adding ${TARGET_USER} to group 'plugdev' ..."
    if id -nG "${TARGET_USER}" | grep -qw plugdev; then
        info "User ${TARGET_USER} is already in plugdev."
    else
        usermod -aG plugdev "${TARGET_USER}"
        info "Added ${TARGET_USER} to plugdev. Log out and back in for this to take effect."
    fi

    info "Reloading udev rules ..."
    udevadm control --reload-rules
    udevadm trigger --subsystem-match=usb --action=add
    info "udev rules reloaded."
}

# ── WSL usbipd-win ────────────────────────────────────────────────────────────

setup_wsl_usbipd() {
    info "WSL detected -- attempting to attach Opella LD via usbipd-win ..."

    if ! command -v usbipd.exe >/dev/null 2>&1; then
        warn "usbipd.exe not found on PATH."
        warn "Install usbipd-win on the Windows host: https://github.com/dorssel/usbipd-win"
        warn "After install, re-run this script to auto-attach the probe."
        return 0
    fi

    # Detect CLI generation: v4+ uses 'usbipd attach', v3 uses 'usbipd wsl attach'.
    if usbipd.exe --help 2>&1 | grep -q "^  attach"; then
        USBIPD_GEN=4
        info "Detected usbipd-win v4+ command layout."
    else
        USBIPD_GEN=3
        info "Detected usbipd-win v3 command layout."
    fi

    # ── WSL kernel USBIP capability check ────────────────────────────────────
    # The Microsoft WSL2 kernel has had USBIP support since 5.10.  However,
    # usbipd-win v3 falsely reports "kernel not USBIP capable" when systemd is
    # enabled in WSL (Ubuntu 22.04+ default).  We pre-load the module and detect
    # this v3+systemd false-negative so we can give a precise error message.
    # Load the client-side USBIP modules needed to receive USB devices from Windows.
    # vhci-hcd creates the virtual USB bus (/dev/bus/usb/); without it lsusb is empty.
    # usbip_host is the server-side module; usbip-core + vhci-hcd are the client side.
    USBIP_MODULE_OK=0
    if sudo modprobe usbip-core >/dev/null 2>&1 &&        sudo modprobe vhci-hcd   >/dev/null 2>&1; then
        USBIP_MODULE_OK=1
        info "USBIP client modules loaded (usbip-core + vhci-hcd)."
    else
        warn "Could not load vhci-hcd kernel module."
        warn "Run: sudo modprobe usbip-core vhci-hcd"
        warn "If that fails, the kernel may lack USBIP support -- run: wsl --update && wsl --shutdown"
        USBIP_MODULE_OK=0
    fi

    # ── bind (one-time, requires Windows admin elevation) ────────────────────
    # We cannot reliably elevate from inside WSL, so we check whether the
    # device is already shared and print manual instructions if not.
    # usbipd list has stable human-readable output across v3/v4/v5;
    # usbipd state was changed to JSON in v5 and is unreliable for grepping.
    if [ "${USBIPD_GEN}" -ge 4 ]; then
        BOUND=$(usbipd.exe list 2>/dev/null | grep -iE "${OPELLA_VID}:${OPELLA_PID}" | grep -iE "Shared|Attached" || true)
    else
        BOUND=$(usbipd.exe wsl list 2>/dev/null | grep -iE "${OPELLA_VID}:${OPELLA_PID}" | grep -iE "Shared|Attached" || true)
    fi

    if [ -z "${BOUND}" ]; then
        warn "Opella LD is not yet bound (shared) in usbipd."
        warn "Run the following command once in an ELEVATED (admin) PowerShell on Windows:"
        warn ""
        warn "  usbipd bind --hardware-id ${OPELLA_VID}:${OPELLA_PID}"
        warn ""
        warn "After binding, re-run this script to attach the probe to WSL."
        return 0
    fi

    # ── attach ────────────────────────────────────────────────────────────────
    info "Attaching ${OPELLA_VID}:${OPELLA_PID} to WSL ..."
    if [ "${USBIPD_GEN}" -ge 4 ]; then
        ATTACH_CMD="usbipd.exe attach --hardware-id ${OPELLA_VID}:${OPELLA_PID} --wsl ${WSL_DISTRO_NAME:-}"
    else
        ATTACH_CMD="usbipd.exe wsl attach --hardware-id ${OPELLA_VID}:${OPELLA_PID}"
    fi

    ATTACH_OUT=$(${ATTACH_CMD} 2>&1 || true)
    # "Attach succeeded" only if output does not look like a usage/error message.
    if echo "${ATTACH_OUT}" | grep -qi "kernel is not USBIP capable"; then
        if [ "${USBIP_MODULE_OK}" -eq 1 ]; then
            # Kernel IS capable (modprobe succeeded) but usbipd disagrees.
            # This is the known usbipd-win v3 + systemd false-negative.
            warn "usbipd-win reported the kernel as not USBIP capable, but the"
            warn "kernel modules loaded fine.  This is a known bug in usbipd-win v3"
            warn "when WSL2 runs with systemd enabled (e.g., Ubuntu 22.04+/24.04)."
            warn ""
            warn "Fix: upgrade usbipd-win to v4 or later."
            warn "  https://github.com/dorssel/usbipd-win/releases"
            warn ""
            warn "usbipd-win v4+ properly supports systemd-enabled WSL2 distros."
        else
            warn "The WSL2 kernel does not have USBIP support."
            warn "Run the following two commands in PowerShell (no elevation needed):"
            warn ""
            warn "  wsl --update"
            warn "  wsl --shutdown"
            warn ""
            warn "Then re-open your WSL terminal and re-run this script."
            warn "If the problem persists after the update, upgrade usbipd-win to v4+:"
            warn "  https://github.com/dorssel/usbipd-win/releases"
        fi
        return 0
    elif echo "${ATTACH_OUT}" | grep -qi "Usage:"; then
        warn "Attach command was not understood (help text returned)."
        warn "This usually means a required flag is missing."
        warn "Attach output: ${ATTACH_OUT}"
        return 0
    elif echo "${ATTACH_OUT}" | grep -qi "VBoxUsbMon"; then
        warn "usbipd VBoxUsbMon driver is missing or broken."
        warn "Note: this is usbipd-win's own internal driver, not VirtualBox."
        warn "Repair usbipd-win in an ELEVATED PowerShell on Windows:"
        warn ""
        warn "    winget uninstall usbipd"
        warn "    winget install usbipd"
        warn ""
        warn "After reinstalling, re-bind and re-run this script:"
        warn "    usbipd bind --hardware-id ${OPELLA_VID}:${OPELLA_PID}"
        warn ""
        warn "If VirtualBox IS installed, try Option B: run the VBox installer and choose Repair."
        return 0
    elif echo "${ATTACH_OUT}" | grep -qiE "error|fail"; then
        warn "Attach failed: ${ATTACH_OUT}"
        warn "Check that the probe is plugged in and bound."
        return 0
    else
        info "Attach succeeded."
    fi

    sleep 1
    if lsusb 2>/dev/null | grep -qi "${OPELLA_VID}:${OPELLA_PID}"; then
        info "Device ${OPELLA_VID}:${OPELLA_PID} visible in /dev/bus/usb -- confirmed."
    else
        warn "Device not yet visible in lsusb. Try re-plugging and re-running."
    fi
}

# ── main ──────────────────────────────────────────────────────────────────────

UDEV_ONLY=0
if [ "${1:-}" = "--udev-only" ]; then
    UDEV_ONLY=1
fi

setup_udev

if [ "${UDEV_ONLY}" -eq 0 ] && is_wsl; then
    setup_wsl_usbipd
fi

echo ""
echo "=== Setup summary ==="
echo "  udev rule : ${UDEV_RULE_FILE}"
echo "  plugdev   : see above"
is_wsl && echo "  usbipd    : attempted (see above)"
echo ""
echo "Next steps:"
echo "  1. Re-plug the Ashling Opella LD."
is_wsl && echo "  2. Re-run this script after each WSL restart to re-attach the probe."
echo "  Verify: ls -l /dev/bus/usb/*/*"
echo "  Then run deploy.sh to flash your application."
