/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#include <stdint.h>
#include <stddef.h>

#define UART_ID_CONSOLE      0U
#define DEBUG_UART           0U

/*
 * ADT7420 temperature calibration offset (units: tenths of a degree Celsius).
 * The on-board sensor reads warm due to FPGA self-heating on the Nexys A7.
 * Measured offset on this board: -3.7 C (-37 in x10 units).
 * Set to 0 to disable calibration.
 */
#define TEMP_CALIBRATION_X10 (-37)
#define FEATURE_CLI_FILESYSTEM 0
#define QAI_CHILKAT          0

intptr_t ql_lw_timer_start(void);
int ql_lw_timer_remain(intptr_t token, int timeout_ms);

#endif /* SDKCONFIG_H */
