/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef ANSI_H
#define ANSI_H

void ansi_clear(void);
void ansi_home(void);
void ansi_clear_screen(void);
void ansi_goto(int row, int col);
void ansi_bold(void);
void ansi_reset_attr(void);
void ansi_green(void);

/* Query actual terminal dimensions via ANSI CPR (ESC[6n).
 * Falls back silently to 80x24 on timeout.
 * Returns 0 on success, -1 on timeout (defaults still set). */
int terminal_probe_size(void);
int terminal_rows(void);
int terminal_cols(void);

/* Print str centered horizontally on row. */
void ansi_center_str(int row, const char *str);

#endif /* ANSI_H */
