/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include "ansi.h"
#include "uart_io.h"

void ansi_clear(void)
{
    uio_puts("[2J");
}

void ansi_home(void)
{
    uio_puts("[H");
}

void ansi_clear_screen(void)
{
    uio_puts("[2J[H");
}

void ansi_goto(int row, int col)
{
    if (row < 1)
    {
        row = 1;
    }
    if (col < 1)
    {
        col = 1;
    }

    uio_printf("[%d;%dH", row, col);
}

void ansi_bold(void)
{
    uio_puts("[1m");
}

void ansi_reset_attr(void)
{
    uio_puts("[0m");
}
