/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef BIG_DIGITS_H
#define BIG_DIGITS_H

#include <stdint.h>

void big_digits_render(int32_t value, int start_row, int start_col);
void big_digits_render_tenths(int32_t value_x10, int start_row, int start_col);

/* Returns the rendered column width (for centering) of big_digits_render_tenths. */
int big_digits_width_tenths(int32_t value_x10);

#endif /* BIG_DIGITS_H */
