/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include <stdint.h>

#include "SDKConfig.h"
#include "slideshow.h"
#include "system_core_v_mcu.h"
#include "temp_sensor.h"
#include "tx_api.h"
#include "uart_driver.h"

#define _TX_STR(x)  #x
#define TX_STR(x)   _TX_STR(x)
#define TX_VERSION_STRING \
    "v" TX_STR(THREADX_MAJOR_VERSION) \
    "." TX_STR(THREADX_MINOR_VERSION) \
    "." TX_STR(THREADX_PATCH_VERSION) \
    "." TX_STR(THREADX_BUILD_VERSION)

#define SLIDESHOW_STACK_SIZE 4096U

static const char tx_banner[] =
    "\r\nEclipse ThreadX for OpenHW CORE-V MCU " TX_VERSION_STRING "\r\n"
    "Copyright (c) 2026 Eclipse ThreadX Contributors\r\n\r\n";

TX_THREAD g_slideshow_thread;
static ULONG g_slideshow_stack[SLIDESHOW_STACK_SIZE / sizeof(ULONG)];

static void error_loop(void)
{
    for (;;)
    {
    }
}

int main(void)
{
    system_init();
    tx_kernel_enter();
    return 0;
}

void tx_application_define(void *first_unused_memory)
{
    UINT status;

    TX_PARAMETER_NOT_USED(first_unused_memory);

    uart_write_str(UART_ID_CONSOLE, tx_banner);
    temp_sensor_init();

    status = tx_thread_create(&g_slideshow_thread, "slideshow", slideshow_thread_entry, 0U,
                              &g_slideshow_stack[0], sizeof(g_slideshow_stack),
                              10U, 10U, TX_NO_TIME_SLICE, TX_AUTO_START);
    if (status != TX_SUCCESS)
    {
        error_loop();
    }
}
