/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef PROGRESS_BAR_H
#define PROGRESS_BAR_H

#include <stdint.h>

void progress_bar_render(int row, uint32_t elapsed_ticks, uint32_t total_ticks, int bar_width);

#endif /* PROGRESS_BAR_H */
