/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include <stdint.h>

#include "ansi.h"
#include "tx_api.h"
#include "uart_io.h"

#define _TX_STR(x)  #x
#define TX_STR(x)   _TX_STR(x)
#define TX_VERSION_STRING \
    "v" TX_STR(THREADX_MAJOR_VERSION) \
    "." TX_STR(THREADX_MINOR_VERSION) \
    "." TX_STR(THREADX_PATCH_VERSION) \
    "." TX_STR(THREADX_BUILD_VERSION)

static const char tx_banner_1[] =
    "Eclipse ThreadX for OpenHW CORE-V MCU " TX_VERSION_STRING;
static const char tx_banner_2[] =
    "Copyright (c) 2026 Eclipse ThreadX Contributors";

void screen_threadx_render(void)
{
    ULONG ticks;
    ULONG tenths;
    int logo_col;

    logo_col = (terminal_cols() - 41) / 2 + 1;
    if (logo_col < 1)
    {
        logo_col = 1;
    }

    ansi_clear_screen();
    ansi_bold();
    ansi_goto(2, logo_col);
    uio_puts("  ________                        ___  __");
    ansi_goto(3, logo_col);
    uio_puts(" /_  __/ /_  ________  ____ _____/ / |/ /");
    ansi_goto(4, logo_col);
    uio_puts("  / / / __ \\/ ___/ _ \\/ __ `/ __  /|   / ");
    ansi_goto(5, logo_col);
    uio_puts(" / / / / / / /  /  __/ /_/ / /_/ //   |  ");
    ansi_goto(6, logo_col);
    uio_puts("/_/ /_/ /_/_/   \\___/\\__,_/\\__,_//_/|_|  ");
    ansi_reset_attr();

    ansi_center_str(8, tx_banner_1);
    ansi_center_str(9, tx_banner_2);

    ticks = tx_time_get();
    tenths = ticks / 10U;
    /* estimate total line width: "System uptime: 99999.9 s" = 25 */
    ansi_goto(11, (terminal_cols() - 25) / 2 + 1);
    uio_puts("System uptime: ");
    uio_put_udec((uint32_t)(tenths / 10U));
    uio_putc('.');
    uio_put_udec((uint32_t)(tenths % 10U));
    uio_puts(" s");
}
