/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include <stdint.h>

#include "ansi.h"
#include "tx_api.h"
#include "uart_io.h"

#define _TX_STR(x)  #x
#define TX_STR(x)   _TX_STR(x)
#define TX_VERSION_STRING \
    "v" TX_STR(THREADX_MAJOR_VERSION) \
    "." TX_STR(THREADX_MINOR_VERSION) \
    "." TX_STR(THREADX_PATCH_VERSION) \
    "." TX_STR(THREADX_BUILD_VERSION)

static const char tx_banner[] =
    "Eclipse ThreadX for OpenHW CORE-V MCU " TX_VERSION_STRING "\r\n"
    "Copyright (c) 2026 Eclipse ThreadX Contributors";

void screen_threadx_render(void)
{
    ULONG ticks;
    ULONG tenths;
    int start_col;
    int logo_width = 41;

    start_col = (terminal_cols() - logo_width) / 2 + 1;
    if (start_col < 1)
    {
        start_col = 1;
    }

    ansi_clear_screen();
    ansi_bold();
    ansi_goto(2, start_col);
    uio_puts("  ________                        ___  __");
    ansi_goto(3, start_col);
    uio_puts(" /_  __/ /_  ________  ____ _____/ / |/ /");
    ansi_goto(4, start_col);
    uio_puts("  / / / __ \\/ ___/ _ \\/ __ `/ __  /|   / ");
    ansi_goto(5, start_col);
    uio_puts(" / / / / / / /  /  __/ /_/ / /_/ //   |  ");
    ansi_goto(6, start_col);
    uio_puts("/_/ /_/ /_/_/   \\___/\\__,_/\\__,_//_/|_|  ");
    ansi_reset_attr();

    ansi_goto(8, start_col);
    uio_puts(tx_banner);

    ticks = tx_time_get();
    tenths = ticks / 10U;
    ansi_goto(11, start_col);
    uio_puts("System uptime: ");
    uio_put_udec((uint32_t)(tenths / 10U));
    uio_putc('.');
    uio_put_udec((uint32_t)(tenths % 10U));
    uio_puts(" seconds");
}
