/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include "ansi.h"
#include "input.h"
#include "progress_bar.h"
#include "slideshow.h"
#include "tx_api.h"

void screen_threadx_render(void);
void screen_openhw_render(void);
void screen_temp_render(void);
void screen_stats_render(void);
void screen_regs_render(void);

#define SLIDE_TICK_STEP 100U
#define TEMP_SLIDE_INDEX 2U
#define PROGRESS_WIDTH 40

static const slide_fn_t s_slides[SLIDE_COUNT] = {
    screen_threadx_render,
    screen_openhw_render,
    screen_temp_render,
    screen_stats_render,
    screen_regs_render
};

static void slideshow_show(unsigned int slide_index, uint32_t elapsed_ticks)
{
    terminal_probe_size();
    s_slides[slide_index]();
    progress_bar_render(terminal_rows() - 1, elapsed_ticks, SLIDE_PERIOD_TICKS, PROGRESS_WIDTH);
}

void slideshow_thread_entry(ULONG arg)
{
    unsigned int slide_index;
    uint32_t elapsed_ticks;
    key_event_t key;

    TX_PARAMETER_NOT_USED(arg);

    slide_index = 0U;
    elapsed_ticks = 0U;
    slideshow_show(slide_index, elapsed_ticks);

    for (;;)
    {
        tx_thread_sleep(SLIDE_TICK_STEP);
        if (elapsed_ticks < SLIDE_PERIOD_TICKS)
        {
            elapsed_ticks += SLIDE_TICK_STEP;
            if (elapsed_ticks > SLIDE_PERIOD_TICKS)
            {
                elapsed_ticks = SLIDE_PERIOD_TICKS;
            }
        }

        key = input_poll();
        if (key == KEY_LEFT)
        {
            slide_index = (slide_index == 0U) ? (SLIDE_COUNT - 1U) : (slide_index - 1U);
            elapsed_ticks = 0U;
            slideshow_show(slide_index, elapsed_ticks);
            continue;
        }
        if ((key == KEY_RIGHT) || (key == KEY_OTHER))
        {
            slide_index = (slide_index + 1U) % SLIDE_COUNT;
            elapsed_ticks = 0U;
            slideshow_show(slide_index, elapsed_ticks);
            continue;
        }
        if (elapsed_ticks >= SLIDE_PERIOD_TICKS)
        {
            slide_index = (slide_index + 1U) % SLIDE_COUNT;
            elapsed_ticks = 0U;
            slideshow_show(slide_index, elapsed_ticks);
            continue;
        }

        if (slide_index == TEMP_SLIDE_INDEX)
        {
            screen_temp_render();
        }
        progress_bar_render(terminal_rows() - 1, elapsed_ticks, SLIDE_PERIOD_TICKS, PROGRESS_WIDTH);
    }
}
