/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef SLIDESHOW_H
#define SLIDESHOW_H

#include "tx_api.h"

#define SLIDE_COUNT         5U
#define SLIDE_PERIOD_TICKS  1000U
#define PROGRESS_ROW        23
#define SCREEN_COLS         80

typedef void (*slide_fn_t)(void);

void slideshow_thread_entry(ULONG arg);

#endif /* SLIDESHOW_H */
