/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#ifndef UART_IO_H
#define UART_IO_H

#include <stdint.h>

void uio_putc(char c);
void uio_puts(const char *s);
void uio_put_dec(int32_t v);
void uio_put_udec(uint32_t v);
void uio_put_hex(uint32_t v, int width);
void uio_put_padded(const char *s, int width);
void uio_printf(const char *fmt, ...);

#endif /* UART_IO_H */
