/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/*
 * Application RAM budget for the PolarFire SoC Icicle Kit.
 *
 * linker.ld lays DRAM out as .text, .data, .bss, the 16 KB boot stack, then
 * __end - which tx_initialize_low_level.S reports as ThreadX's first unused
 * address. Unlike a Cortex-M board there is no stack at the top of RAM to hold
 * back, because the boot stack sits below __end; the only reservation above it
 * is the newlib heap, which _sbrk() grows up from __end towards
 * BSP_HEAP_LIMIT. Everything above that reservation is the application's.
 */

#include <stdint.h>

#include "bsp/memory.h"
#include "board_config.h"

/* ThreadX wants an aligned pool base, and linker.ld aligns its sections to 16
 * bytes, so the region starts on the same boundary. */
#define BSP_RAM_REGION_ALIGN    16U

void bsp_ram_region(void *first_unused, void **base, size_t *size)
{
    /*
     * MISRA C:2012 Rule 11.4 deviation: converting between a pointer and an
     * integer is unavoidable here. Clamping against the heap reservation and
     * the end of DRAM is arithmetic on absolute addresses, which C cannot
     * express on pointers to distinct objects.
     */
    uintptr_t start = (uintptr_t)first_unused;

    /* Never hand out the heap reservation, wherever ThreadX believes free
     * memory begins. */
    if (start < BSP_HEAP_LIMIT) {
        start = BSP_HEAP_LIMIT;
    }

    start = (start + (BSP_RAM_REGION_ALIGN - 1U)) &
            ~(uintptr_t)(BSP_RAM_REGION_ALIGN - 1U);

    *base = (void *)start;
    *size = ((uintptr_t)BSP_RAM_END > start)
                ? (size_t)((uintptr_t)BSP_RAM_END - start)
                : (size_t)0U;
}
