/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/*
 * Startup self-tests for the PolarFire SoC Icicle Kit.
 *
 * These check the board support package - the bounds its heap enforces, the
 * CLINT arithmetic its timebase relies on, the PLIC routing its console
 * interrupt needs - so they live with the board rather than with any
 * application. The application supplies only the reporting callback, which is
 * why this translation unit can include plic.h, hwtimer.h and csr.h without
 * dragging any of them into an application.
 *
 * Every check runs before tx_kernel_enter(), so a failure is reported even
 * when the scheduler never starts.
 */

#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "bsp/memory.h"
#include "bsp/selftest.h"
#include "board_config.h"
#include "csr.h"
#include "hwtimer.h"
#include "plic.h"

/* Defined in app/common/startup/newlib_stubs.c, which newlib declares only in
 * its private headers. */
extern void *_sbrk(ptrdiff_t incr);

/* Reporting state, kept on the caller's stack so bsp_self_test() holds no
 * mutable state of its own. */
typedef struct {
    bsp_selftest_report_fn report;
    void                  *context;
    unsigned               failures;
} selftest_state;

static void check(selftest_state *state, int passed, const char *message)
{
    if (passed == 0) {
        state->failures++;
    }
    state->report(passed, message, state->context);
}

unsigned bsp_self_test(bsp_selftest_report_fn report, void *context)
{
    selftest_state state;
    char           msg[160];

    void   *region_base = NULL;
    size_t  region_size = 0U;
    void   *p1;
    void   *p_under;
    void   *p_over;
    void   *p_past_heap;
    uint64_t now;
    uint64_t missed_cmp;
    uint64_t pending_cmp;
    uint32_t prio;
    uint32_t en_bitmap;
    uint32_t thresh;
    uint64_t mie_val;
    int      clamp_ok;
    int      plic_ok;

    if (report == NULL) {
        return 1U;
    }

    state.report   = report;
    state.context  = context;
    state.failures = 0U;

    /* 1. _sbrk() valid allocation test. */
    p1 = _sbrk(64);
    check(&state, (p1 != (void *)-1) && ((uintptr_t)p1 >= BSP_HEAP_BASE),
          "_sbrk() valid allocation returned base pointer");

    /* 2. _sbrk() underflow test (shrink below the heap base). */
    errno = 0;
    p_under = _sbrk(-128);
    check(&state, (p_under == (void *)-1) && (errno == EINVAL),
          "_sbrk() underflow guard rejected with EINVAL");

    /* 3. _sbrk() overflow test (request beyond the 1 GiB DRAM). */
    errno = 0;
    p_over = _sbrk((ptrdiff_t)0x40000000ULL);
    check(&state, (p_over == (void *)-1) && (errno == ENOMEM),
          "_sbrk() overflow guard rejected with ENOMEM");

    /* 4. Regression guard for the heap bound. This request fits DRAM with a
     * gigabyte to spare but exceeds the heap reservation, so bounding _sbrk()
     * against BSP_RAM_END rather than BSP_HEAP_LIMIT lets it succeed and hands
     * malloc() memory bsp_ram_region() has already promised the application. */
    errno = 0;
    p_past_heap = _sbrk((ptrdiff_t)(BSP_HEAP_RESERVE_BYTES + 0x1000ULL));
    check(&state, (p_past_heap == (void *)-1) && (errno == ENOMEM),
          "_sbrk() rejects a request that fits DRAM but not the heap");

    /* 5. The region bsp_ram_region() hands the application must start above
     * the heap reservation and end inside DRAM. This is the invariant that
     * keeps malloc() and a ThreadX byte pool from ever overlapping. */
    bsp_ram_region(&__end, &region_base, &region_size);
    (void)snprintf(msg, sizeof(msg),
                   "bsp_ram_region() yields [0x%llX,0x%llX), clear of the heap and inside DRAM",
                   (unsigned long long)(uintptr_t)region_base,
                   (unsigned long long)((uintptr_t)region_base + region_size));
    check(&state,
          (region_size > 0U) && ((uintptr_t)region_base >= BSP_HEAP_LIMIT) &&
              (((uintptr_t)region_base + region_size) <= (uintptr_t)BSP_RAM_END),
          msg);

    /* 6. HWTimer catch-up clamp.
     *
     * Exercised as pure arithmetic through hwtimer_next_cmp(), so no CLINT
     * register is disturbed: mtime is the platform-wide counter shared by every
     * hart, and mtimecmp drives the live kernel tick. Both branches are covered
     * - a deadline still in the future advances relatively, one already missed
     * is rebased onto the current time instead of firing continuously. */
    now = 5000000ULL;
    missed_cmp = now - (TICK_CYCLES * 8ULL);   /* 8 ticks behind */
    pending_cmp = now - (TICK_CYCLES / 2ULL);  /* deadline not yet due */
    clamp_ok = (hwtimer_next_cmp(missed_cmp, now) == now + TICK_CYCLES) &&
               (hwtimer_next_cmp(pending_cmp, now) == pending_cmp + TICK_CYCLES);
    (void)snprintf(msg, sizeof(msg),
                   "HWTimer catch-up (missed deadline rebased to %llu, pending deadline advanced to %llu)",
                   (unsigned long long)hwtimer_next_cmp(missed_cmp, now),
                   (unsigned long long)hwtimer_next_cmp(pending_cmp, now));
    check(&state, clamp_ok, msg);

    /* 7. PLIC configuration and addressing verification.
     * A wrong PLIC base would read back zeroes here, so the register values
     * confirm the addressing as well as the configuration. */
    prio = PLIC_PRIORITY_REG(MMUART1_IRQ);
    en_bitmap = PLIC_HART1_M_ENABLE_REG(MMUART1_IRQ);
    thresh = PLIC_HART1_M_THRESHOLD_REG;
    __asm__ volatile("csrr %0, mie" : "=r"(mie_val));

    plic_ok = (prio == 1) &&
              ((en_bitmap & (1U << (MMUART1_IRQ % 32))) != 0) &&
              (thresh == 0) &&
              ((mie_val & MIE_MEIE) != 0);
    (void)snprintf(msg, sizeof(msg),
                   "PLIC Hart 1 (IRQ %u prio=%u en=0x%08X thresh=%u mie=0x%llX)",
                   (unsigned)MMUART1_IRQ, (unsigned)prio, (unsigned)en_bitmap,
                   (unsigned)thresh, (unsigned long long)mie_val);
    check(&state, plic_ok, msg);

    return state.failures;
}
