/***************************************************************************/
/* Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include "cli_mock.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#define CLI_MOCK_BUFFER_SIZE 256U

static char cli_mock_buffer[CLI_MOCK_BUFFER_SIZE];

/* Reset the captured CLI output buffer. */
void cli_mock_reset(void)
{
    (void)memset(cli_mock_buffer, 0, sizeof(cli_mock_buffer));
}

/* Return the captured CLI output buffer. */
const char *cli_mock_get_output(void)
{
    return &cli_mock_buffer[0];
}

/* Capture CLI_printf output for host-side unit tests. */
void CLI_printf(const char *fmt, ...)
{
    va_list ap;
    size_t used;
    int written;

    used = strlen(cli_mock_buffer);
    if (used >= (sizeof(cli_mock_buffer) - 1U))
    {
        return;
    }

    va_start(ap, fmt);
    written = vsnprintf(&cli_mock_buffer[used], sizeof(cli_mock_buffer) - used, fmt, ap);
    va_end(ap);

    if (written < 0)
    {
        cli_mock_buffer[used] = '\0';
    }
}
