#!/usr/bin/env bash
# /***************************************************************************/
# /* Copyright (C) 2026 Eclipse ThreadX contributors
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the MIT License which is available at
#  * https://opensource.org/licenses/MIT.
#  *
#  * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
#  * The AI-generated portions may be considered public domain (CC0-1.0)
#  * and not subject to the project's licence.
#  *
#  * SPDX-License-Identifier: MIT AND CC0-1.0
#  ***************************************************************************/

# deploy.sh -- build (optionally), flash, and run/debug the CORE-V MCU target
# via the Ashling Opella LD debug probe.
#
# Usage:
#   bash deploy.sh [options]
#
# Options:
#   --build             Run build.sh before flashing (default: skip).
#   --debug             After loading, stop at main and leave GDB attached
#                       (default: run free and exit GDB).
#   --elf <path>        Override the ELF to flash
#                       (default: build/core_v_mcu_slideshow.elf).
#   --openocd-cfg <p>   Override the OpenOCD config file.
#
# Prerequisites:
#   * riscv64-unknown-elf-gdb and openocd must be on PATH.
#   * Run setup_opella.sh once to configure udev rules.
#   * The Nexys A7 board must be powered on.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
if command -v riscv64-unknown-elf-gdb >/dev/null 2>&1; then
    GDB="riscv64-unknown-elf-gdb"
elif command -v gdb-multiarch >/dev/null 2>&1; then
    GDB="gdb-multiarch"
else
    GDB="riscv64-unknown-elf-gdb"
fi
OPENOCD_LOG="${PROJECT_DIR}/.openocd_slideshow.log"
GDB_INIT_FILE="${PROJECT_DIR}/.gdb_deploy_slideshow.gdb"
OPENOCD_PID=""
OPENOCD_TIMEOUT=10

DEFAULT_ELF="${PROJECT_DIR}/build/core_v_mcu_slideshow.elf"
DEFAULT_CFG="${PROJECT_DIR}/../../libs/threadx/ports/risc-v32/gnu/example_build/core_v_mcu/openocd-nexys-Ashling-Opella-LD.cfg"

OPT_BUILD=0
OPT_DEBUG=0
OPT_ELF=""
OPT_CFG=""

usage() { grep '^# ' "$0" | sed 's/^# //' | head -30; exit 0; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --build)       OPT_BUILD=1; shift ;;
        --debug)       OPT_DEBUG=1; shift ;;
        --elf)         OPT_ELF="$2"; shift 2 ;;
        --openocd-cfg) OPT_CFG="$2"; shift 2 ;;
        -h|--help)     usage ;;
        *) echo "[ERROR] Unknown option: $1" >&2; usage ;;
    esac
done

ELF="${OPT_ELF:-${DEFAULT_ELF}}"
CFG="${OPT_CFG:-${DEFAULT_CFG}}"

info()  { echo "[INFO]  $*"; }
die()   { echo "[ERROR] $*" >&2; exit 1; }

stop_openocd() {
    if [ -n "${OPENOCD_PID}" ] && kill -0 "${OPENOCD_PID}" 2>/dev/null; then
        info "Stopping OpenOCD (PID ${OPENOCD_PID}) ..."
        kill "${OPENOCD_PID}" 2>/dev/null || true
        wait "${OPENOCD_PID}" 2>/dev/null || true
    fi
}

trap stop_openocd EXIT INT TERM

if [ "${OPT_BUILD}" -eq 1 ]; then
    info "Running build.sh ..."
    bash "${SCRIPT_DIR}/build.sh"
fi

[ -f "${ELF}" ] || die "ELF not found: ${ELF}  (run with --build to build first)"
[ -f "${CFG}" ] || die "OpenOCD config not found: ${CFG}"
command -v openocd >/dev/null 2>&1 || die "openocd not found on PATH"
command -v "${GDB}" >/dev/null 2>&1 || die "${GDB} not found on PATH"

info "Starting OpenOCD with config: ${CFG}"
info "Log: ${OPENOCD_LOG}"
openocd -f "${CFG}" >"${OPENOCD_LOG}" 2>&1 &
OPENOCD_PID=$!

info "Waiting for OpenOCD to be ready (up to ${OPENOCD_TIMEOUT}s) ..."
ELAPSED=0
while ! grep -q "Ready for Remote Connections" "${OPENOCD_LOG}" 2>/dev/null; do
    sleep 1
    ELAPSED=$((ELAPSED + 1))
    if [ "${ELAPSED}" -ge "${OPENOCD_TIMEOUT}" ]; then
        echo "--- OpenOCD log ---" && cat "${OPENOCD_LOG}"
        die "OpenOCD did not become ready within ${OPENOCD_TIMEOUT}s"
    fi
    if ! kill -0 "${OPENOCD_PID}" 2>/dev/null; then
        echo "--- OpenOCD log ---" && cat "${OPENOCD_LOG}"
        die "OpenOCD exited unexpectedly"
    fi
done
info "OpenOCD is ready."

printf 'set confirm off\nset remotetimeout 60\nfile %s\ntarget extended-remote localhost:3333\nload\n' \
    "${ELF}" > "${GDB_INIT_FILE}"

if [ "${OPT_DEBUG}" -eq 0 ]; then
    info "Flashing and running (detached) ..."
    printf 'monitor resume\ndisconnect\nquit\n' >> "${GDB_INIT_FILE}"
    info "ELF: ${ELF}"
    riscv64-unknown-elf-size "${ELF}"
    "${GDB}" --batch --command="${GDB_INIT_FILE}"
    info "Flash complete. Application is running on the target."
    info "Serial console: minicom -b 115200 -D /dev/ttyUSBx"
else
    info "Flashing and stopping at main for interactive debug ..."
    printf 'break main\ncontinue\n' >> "${GDB_INIT_FILE}"
    info "ELF: ${ELF}"
    riscv64-unknown-elf-size "${ELF}"
    "${GDB}" --command="${GDB_INIT_FILE}"
fi
