/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/*
 * Application RAM budget for the NUCLEO-F401RE.
 *
 * NUCLEO_F401RE.ld lays SRAM out as .data, .bss, the newlib heap reservation
 * and _Min_Stack_Size, then __RAM_segment_used_end__ - which is what
 * tx_initialize_low_level.S reports as ThreadX's first unused address. The
 * main stack grows down from _estack at the top of SRAM, so the region between
 * the two is what the application may claim.
 */

#include <stdint.h>

#include "bsp/memory.h"
#include "board_config.h"

void bsp_ram_region(void *first_unused, void **base, size_t *size)
{
    /*
     * MISRA C:2012 Rule 11.4 deviation: converting between a pointer and an
     * integer is unavoidable here. The comparison against BSP_RAM_END is
     * arithmetic on absolute addresses, which C cannot express on pointers to
     * distinct objects.
     */
    const uintptr_t start = (uintptr_t)first_unused;
    const uintptr_t end   = (uintptr_t)BSP_RAM_END -
                            (uintptr_t)BSP_MAIN_STACK_RESERVE;

    *base = first_unused;
    *size = (end > start) ? (size_t)(end - start) : (size_t)0U;
}
