/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "bsp/led.h"
#include "board_config.h"
#include "stm32f4xx_hal.h"

#define NUCLEO_LED_PIN          GPIO_PIN_5
#define NUCLEO_LED_GPIO_PORT    GPIOA

void bsp_led_init(void)
{
#if BSP_HAS_LED
    GPIO_InitTypeDef gpio = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();

    gpio.Pin   = NUCLEO_LED_PIN;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(NUCLEO_LED_GPIO_PORT, &gpio);

    bsp_led_off();
#endif
}

void bsp_led_on(void)
{
#if BSP_HAS_LED
    HAL_GPIO_WritePin(NUCLEO_LED_GPIO_PORT, NUCLEO_LED_PIN, GPIO_PIN_SET);
#endif
}

void bsp_led_off(void)
{
#if BSP_HAS_LED
    HAL_GPIO_WritePin(NUCLEO_LED_GPIO_PORT, NUCLEO_LED_PIN, GPIO_PIN_RESET);
#endif
}

void bsp_led_toggle(void)
{
#if BSP_HAS_LED
    HAL_GPIO_TogglePin(NUCLEO_LED_GPIO_PORT, NUCLEO_LED_PIN);
#endif
}
