/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef BSP_MEMORY_H
#define BSP_MEMORY_H

#include <stddef.h>

/**
 * @brief Reports the RAM region the application may claim.
 *
 * ThreadX hands tx_application_define() the first address it believes to be
 * unused, but only the board knows what sits above it: a C heap reservation, a
 * main stack at the top of RAM, or a memory-mapped peripheral window. This
 * call clamps the region against whatever the board holds back, so an
 * application can size a TX_BYTE_POOL without naming a single board symbol.
 *
 * The returned region is the application's to divide up. A board must never
 * include its own heap or stack reservations in it.
 *
 * @param first_unused The pointer ThreadX passed to tx_application_define().
 * @param base Receives the first address the application owns. Must not be
 *             NULL.
 * @param size Receives the length of that region in bytes, zero when the board
 *             has no RAM to spare. Must not be NULL.
 */
void bsp_ram_region(void *first_unused, void **base, size_t *size);

#endif /* BSP_MEMORY_H */
