/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef BSP_SELFTEST_H
#define BSP_SELFTEST_H

/**
 * @brief Reports the outcome of one board self-test.
 *
 * The board owns the checks; the application owns how their results reach the
 * user. Formatting the line - and therefore the choice between printf() and
 * bsp_console_write() - stays entirely on the application side of this
 * callback, so a board never has to know which is available.
 *
 * @param passed  Non-zero when the check succeeded, zero when it failed.
 * @param message Description of the check, including any measured values.
 *                Valid only for the duration of the call.
 * @param context The context pointer that was handed to bsp_self_test().
 */
typedef void (*bsp_selftest_report_fn)(int passed, const char *message,
                                       void *context);

/**
 * @brief Runs the board's startup self-tests.
 *
 * Intended to be called before tx_kernel_enter(), so a hardware or runtime
 * fault is reported even when the scheduler never starts. Each check reports
 * through @p report in execution order; checks that mutate board state undo it
 * before returning, leaving the board as the caller found it.
 *
 * @param report  Callback invoked once per check. Must not be NULL; passing
 *                NULL runs no check and returns 1, since a board whose results
 *                cannot be reported must not be assumed healthy.
 * @param context Opaque pointer passed back to @p report unmodified.
 * @return Number of checks that failed; zero when every check passed.
 */
unsigned bsp_self_test(bsp_selftest_report_fn report, void *context);

#endif /* BSP_SELFTEST_H */
